export const events = [
  {
    id: "ia",
    title: "Inteligencia artificial para la vida diaria",
    category: "Tecnología",
    date: "2026-09-23",
    start: "10:00",
    end: "11:30",
    location: "Encuentro virtual",
  },
  {
    id: "aprendizaje",
    title: "Aprender en línea: herramientas y hábitos",
    category: "Educación",
    date: "2026-09-26",
    start: "09:00",
    end: "11:00",
    location: "Taller virtual",
  },
  {
    id: "turismo",
    title: "Rutas de turismo sostenible en Colombia",
    category: "Turismo",
    date: "2026-10-03",
    start: "14:00",
    end: "16:00",
    location: "Conversatorio virtual",
  },
  {
    id: "seguridad",
    title: "Protege tu información en internet",
    category: "Tecnología",
    date: "2026-10-08",
    start: "16:00",
    end: "17:30",
    location: "Taller virtual",
  },
  {
    id: "lectura",
    title: "Lectura y bibliotecas para todos",
    category: "Educación",
    date: "2026-10-17",
    start: "10:00",
    end: "12:00",
    location: "Encuentro virtual",
  },
  {
    id: "comunidad",
    title: "Comunidades que construyen ciudades verdes",
    category: "Actualidad",
    date: "2026-10-24",
    start: "09:00",
    end: "10:30",
    location: "Foro virtual",
  },
] as const;
